import type { Invite, Project, User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u1",
    name: "Maya Rodriguez",
    skills: ["React", "TypeScript", "UI Design"],
    interests: ["Fintech", "Design Systems"],
    availability: "10-20 hrs/week",
    experienceLevel: "Advanced",
    projectTypesInterested: ["Hackathon", "Startup"],
  },
  {
    id: "u2",
    name: "Dev Patel",
    skills: ["Data Engineering", "Python", "SQL"],
    interests: ["Climate", "Analytics"],
    availability: "5-10 hrs/week",
    experienceLevel: "Intermediate",
    projectTypesInterested: ["Research", "Open Source"],
  },
  {
    id: "u3",
    name: "Aisha Khan",
    skills: ["ML", "Python", "Research"],
    interests: ["Health", "Climate"],
    availability: "20+ hrs/week",
    experienceLevel: "Expert",
    projectTypesInterested: ["Research", "Startup"],
  },
  {
    id: "u4",
    name: "Leo Fischer",
    skills: ["Backend", "Node.js", "Postgres"],
    interests: ["Fintech", "Infrastructure"],
    availability: "10-20 hrs/week",
    experienceLevel: "Advanced",
    projectTypesInterested: ["Startup", "Freelance-style"],
  },
  {
    id: "u5",
    name: "Sana Iyer",
    skills: ["UX Design", "User Research", "Figma"],
    interests: ["Health", "Accessibility"],
    availability: "5-10 hrs/week",
    experienceLevel: "Intermediate",
    projectTypesInterested: ["Hackathon", "Competition"],
  },
  {
    id: "u6",
    name: "Marcus Doyle",
    skills: ["Product", "Growth", "Analytics"],
    interests: ["Fintech", "Marketplaces"],
    availability: "< 5 hrs/week",
    experienceLevel: "Expert",
    projectTypesInterested: ["Startup"],
  },
  {
    id: "u7",
    name: "Yuki Tanaka",
    skills: ["React", "Mobile", "Animation"],
    interests: ["Climate", "Games"],
    availability: "20+ hrs/week",
    experienceLevel: "Beginner",
    projectTypesInterested: ["Hackathon", "Open Source"],
  },
  {
    id: "u8",
    name: "Priya Nair",
    skills: ["DevOps", "Backend", "Security"],
    interests: ["Infrastructure", "Fintech"],
    availability: "10-20 hrs/week",
    experienceLevel: "Advanced",
    projectTypesInterested: ["Startup", "Competition"],
  },
];

export const seedProjects: Project[] = [
  {
    id: "p1",
    title: "CarbonLedger",
    description:
      "A climate analytics dashboard that turns messy emissions data into clear, auditable reports for small manufacturers.",
    leaderName: "Nora Vance",
    leaderExperience: "Advanced",
    requiredSkills: ["React", "Data Engineering", "UX Design", "Backend"],
    teamSize: 5,
    duration: "3 months",
    location: "Berlin",
    remoteOk: true,
    additionalInfo: "Weekly syncs Thursdays. Equity split discussed once we ship an MVP.",
    projectType: "Startup",
  },
  {
    id: "p2",
    title: "MediScribe",
    description:
      "Hackathon build: an ML assistant that drafts clinical notes from doctor-patient audio, with a strong health privacy focus.",
    leaderName: "Omar Haddad",
    leaderExperience: "Expert",
    requiredSkills: ["ML", "Python", "UI Design", "Product"],
    teamSize: 4,
    duration: "1 week",
    location: "Remote",
    remoteOk: true,
    additionalInfo: "48-hour hackathon sprint, then optional continuation.",
    projectType: "Hackathon",
  },
  {
    id: "p3",
    title: "OpenTransit Atlas",
    description:
      "Open source mapping of informal transit routes, built with community-collected GPS traces and a public API.",
    leaderName: "Grace Lim",
    leaderExperience: "Intermediate",
    requiredSkills: ["Backend", "SQL", "React", "DevOps"],
    teamSize: 6,
    duration: "Ongoing",
    location: "Nairobi",
    remoteOk: true,
    additionalInfo: "Fully volunteer, MIT licensed. Great for portfolio work.",
    projectType: "Open Source",
  },
];

export const seedInvites: Invite[] = [
  { id: "i1", projectId: "p2", userId: "u3", direction: "leader_to_candidate", status: "pending" },
  { id: "i2", projectId: "p1", userId: "u5", direction: "candidate_to_leader", status: "pending" },
];
